# Project information
site_name: LoopFollowDocs
site_description: Documentation of LoopFollow, a companion for Loop and Trio AID systems for iOS.
#site_url: https://loopfollowdocs.org/
site_author: LoopFollow Community
use_directory_urls: !ENV [CHECK_BROKEN_LINKS, True]

# GitHub Repository
repo_name: loopandlearn/loopfollowdocs
#repo_url: https://github.com/loopandlearn/loopfollowdocs/
#edit_uri: edit/dev/docs/

copyright: LoopFollow Community

theme:
  name: material
  language: en
  #custom_dir: overrides
  logo: assets/images/loopfollow-logo.png
  favicon: assets/images/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: medium blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: medium blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: medium blue
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to auto (use System Preferences)
  features:
    - announce.dismiss
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow

plugins:
  - redirects:
      redirect_maps:
      #  'startup-guide.md': 'configuration/new-user-setup.md'
      #  'startup-guide/index.md': 'configuration/new-user-setup.md'
  - open-in-new-tab
  - macros
  - exporter:
      formats:
        pdf:
          enabled: !ENV [MKDOCS_EXPORTER_PDF, false]
          concurrency: 16
          stylesheets:
            - docs/assets/stylesheets/pdf.scss
          covers:
            front: docs/assets/templates/covers/front.html.j2
            # back: docs/assets/templates/covers/back.html.j2
          aggregator:
            enabled: true
            output: loopfollowdocs.pdf
            covers: limits
      buttons:
        - title: Download Page as PDF
          icon: material-file-download-outline
          enabled: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.enabled
          attributes: !!python/name:mkdocs_exporter.formats.pdf.buttons.download.attributes
  - htmlproofer:
      enabled: !ENV [CHECK_BROKEN_LINKS, False]
      raise_error_after_finish: true
  - include-markdown:
      start: <!--include-markdown-start-->
      end: <!--include-markdown-end-->
  - unused_files:
      enabled: !ENV [CHECK_UNUSED_FILES, False]
      strict: true
      excluded_files:
        - back.html.j2
        - background.png
        - CNAME
        - .DS_Store
        - extra.css
        - favicon.ico
        - front.html.j2
        - .keep
        - mathjax.js
        - mkdocs-exporter.js
        - pdf.scss
        - primary_color.css
        - loopfollowdocs.pdf
  - search

extra_css:
  - assets/stylesheets/primary_color.css
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/mkdocs-exporter.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.9.1/mermaid.min.js

# Customizations
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/loopandlearn/LoopFollow
      name: LoopFollow on GitHub
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/loopfollowlnl
      name: LoopFollow on Facebook
  version: 0.4.0

watch:
  - includes

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      #options:
      #  custom_icons:
      #    - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.txt
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      permalink_title: Link to this section for reference
      title: On this Page
      toc_depth: 3

exclude_docs: |
  /includes/

not_in_nav: |

# Navigation (Page tree)
nav:
- Home: 'index.md'
- Setup:
  - 'LoopFollow Setup': 'setup/lf-setup.md'
- Features:
  - 'LoopFollow Features': 'features/lf-features-overview.md'
  - 'LoopFollow Remote Control Overview': 'features/remote-control-overview.md'
  - 'LoopFollow Loop Remote Control': 'features/remote-control-loop.md'
  - 'LoopFollow Trio Remote Control': 'features/remote-control-trio.md'
- Build:
  - 'LoopFollow Build': 'build/build-options.md'
- FAQs:
  - 'LoopFollow FAQs': 'faqs/lf-faqs.md'
  - 'Glossary': faqs/glossary.md
- Translate:
  - 'Translation': 'translate.md'

